version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Running tests...
      - npm test
      - echo Packaging application...
      - zip -r app.zip .
artifacts:
  files:
    - app.zip
